### PR TITLE
unnamed

### PR DESCRIPTION
**Pull request by Razip**

### CODE REVIEW

**Comment by Razip** [comment]
Damn, it needs to be in https://github.com/r3lgar/r3lgar-session xD

**Comment by Derlafff** [comment]
wut

**Comment by derlaft** [comment]
wut

**Comment by Razip** [comment]
I wanted to say hi to r3lgar in a funny way here, on Github, because I couldn't find his contacts but I accidentally posted that on your repository instead of his.

Sorry for bothering you.

**Pull request closed without merging**
